version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123!
      - POSTGRES_DB=fastapi_week10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend/my-app
    ports:
      - "3000:80"
    depends_on:
      - backend



volumes:
  postgres_data:
